### ISSUE TITLE
Blank maps

### ISSUE THREAD

**Issue by bstar16** [haq/mapcha#4]
Maps just blank when right clicked

**Comment by bstar16** [comment]
a fork of paper spigot

**Comment by haq** [comment]
> a fork of paper spigot

can you provide me with a link, so I can test and fix the bug?

**Comment by bstar16** [comment]
https://github.com/nopjmp/Dionysus

**Comment by haq** [comment]
> https://github.com/nopjmp/Dionysus

I just tested with [Dionysus v0.1.7](https://github.com/nopjmp/Dionysus/releases/tag/v0.1.7) and everything is working fine.
