### ISSUE TITLE
[Suggestion] could you implement something like set map to certain hotbar slot on join

### ISSUE THREAD

**Issue by kokqi** [haq/mapcha#9]
and allow editing the map lore
![image](https://user-images.githubusercontent.com/78592988/233685095-9ecc3c4c-7502-49a7-832a-c05304c35c85.png)

**Comment by kokqi** [comment]
could you implement something like set map to certain hotbar slot on join, and also fix throwing maps, walking freely etc

**Comment by kokqi** [comment]
and adjust font size

**Comment by haq** [comment]
24a42fe33d8bd13419f922a246ebf987ff1685c1
01a32dcc73a76beb4ddf3513dde04d7f59ccdf5d
cef7089bb2371c40a2e4fab8c19f1845a0de2ae7
038101e4cdd79db2bb74917375c8ea51974eb7b6

**Comment by haq** [comment]
https://github.com/haq/mapcha/releases/tag/2.3
